- name: Install modules 
  hosts: localhost
  vars:
    go_version: "1.21.2"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/zsh.yml
    - include: tasks/ssh.yml
    - include: tasks/git.yml
    - include: tasks/core-setup.yml
    - include: tasks/node.yml
    - include: tasks/npm-packages.yml
    - include: tasks/go.yml
    - include: tasks/rust.yml
    - include: tasks/dotnet.yml
    - include: tasks/dotfiles.yml
    - include: tasks/nvim.yml

