- name: Install modules 
  hosts: localhost
  vars:
    go_version: "1.21.2"
  tags:
    - install
  tasks:
    - include: tasks/zsh.yml
    - include: tasks/tmux.yml
    - include: tasks/dotfiles.yml
    - include: tasks/nvim.yml
    - include: tasks/go.yml
    #    - include: tasks/node.yml

