- name: Install System Packages 1 
  become: true
  apt:
    name: ["stow"] 
  tags:
    - install
    - core
    - dotfiles 
    - stow 

- name: Stow dotfiles
  become_user: nilsse
  become: true
  shell: cd $HOME/.dotfiles && ./stow.sh
  tags:
    - install
    - core
    - dotfiles 
    - stow 







