- name: Git personal setup email
  become: true 
  become_user: nilsse
  git_config:
    name: user.email
    scope: global
    value: "nilsselbach@live.de"
  tags:
  - git-personal
- name: Git personal setup name
  become: true 
  become_user: nilsse
  git_config:
    name: user.name
    scope: global
    value: "Nils Selbach"
  tags:
  - git-personal
