- name: Remove neovim
  shell: rm -rf ~/neovim
  become: true
  become_user: nilsse
  tags:
    - install
    - neovim

- name: Clone Neovim
  become: true
  become_user: nilsse
  ansible.builtin.git:
    depth: 1
    repo: "https://github.com/neovim/neovim.git"
    dest: "~/neovim"
  tags:
    - install
    - neovim

- name: Build neovim
  become: true
  become_user: nilsse
  shell: "cd ~/neovim && sudo make CMAKE_BUILD_TYPE=RelWithDebInfo"
  tags:
    - install
    - neovim

- name: Install neovim
  become: true
  become_user: nilsse
  shell: "cd ~/neovim && sudo make install"
  tags:
    - install
    - neovim
