#!/usr/bin/env bash
alias my_ip="ip address | grep -o \"inet 192.*/\" | awk '{ print \$2 }' | tr / ' ' | xargs"

#!/usr/bin/env bash
alias vim="$VIM"
alias vims="NVIM_LISTEN_ADDRESS=/tmp/nvim $VIM"
alias kill_netflix="pkill -9 GIBBON_MAIN"
alias work="cd ~/work"
alias cme="cd ~"

alias python="python3"
alias ev="$VIM ~/.config/nvim"
alias cbp="cat $DOTFILES/zsh/.config/.zsh_profile"
alias ebp="$VIM $DOTFILES/.zsh_profile"
alias bp="dotFileInstall && source ~/.zshrc"
alias cvrc="cat $DOTFILES/vimrc/.vimrc"
